name: 添加功能
description: 请填写希望添加的功能的具体信息
title: 【添加功能】请填写标题
labels: [add]
body:
  - type: input
    id: name
    validations:
      required: true
    attributes:
      label: "希望添加什么功能？"
      placeholder: "请填写功能名称"
  - type: textarea
    id: other
    attributes:
      label: "具体信息"
      description: "请详细描述希望添加的功能的具体信息"
